services:
  app:
    build: .
    ports:
      - "${APP_PORT:-3042}:${PORT:-3042}"
    depends_on:
      - postgres
    environment:
      - PORT=${PORT:-3042}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-balance_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    restart: unless-stopped
    command: npm start

  postgres:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT:-5437}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-balance_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 